name: Cross-Platform Build and Test

on: [workflow_dispatch, pull_request]

jobs:
  linux-debug:
    uses: ./.github/workflows/generic-jobs.yml
    with:
      os: ubuntu-latest
      build_type: debug

  linux-release:
    uses: ./.github/workflows/generic-jobs.yml
    with:
      os: ubuntu-latest
      build_type: release

  windows-debug:
    uses: ./.github/workflows/generic-jobs.yml
    with:
      os: windows-latest
      build_type: debug

  windows-release:
    uses: ./.github/workflows/generic-jobs.yml
    with:
      os: windows-latest
      build_type: release

  macos-debug:
    uses: ./.github/workflows/generic-jobs.yml
    with:
      os: macos-latest
      build_type: debug

  macos-release:
    uses: ./.github/workflows/generic-jobs.yml
    with:
      os: macos-latest
      build_type: release
